DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS accounts;

CREATE TABLE posts(
    id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    user_id VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL,
    img VARCHAR(255) NOT NULL,
    date VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    content VARCHAR(5000) NOT NULL,
    tag VARCHAR(255) NOT NULL
);

CREATE TABLE accounts (
	id int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id varchar(50) UNIQUE NOT NULL,
    email varchar(100) UNIQUE NOT NULL,
  	username varchar(50) UNIQUE NOT NULL,
  	password varchar(255) UNIQUE NOT NULL
);